title: "MN Booth"
email: "info@mnbooth.com"
description: >- # this means to ignore newlines until "baseurl:"
 MN Booth - An affordable event photo booth provider serving Minneapolis and surrounding cities.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://mnbooth.com" # the base hostname & protocol for your site, e.g. http://example.com # https://addzone-jk.netlify.com
facebook_url: https://www.facebook.com/mnbooth
instagram_url: http://instagram.com/mnbooth
logo: "/assets/images/logo/logo.png"
logo_2: "/assets/images/logo/logo.png"
google_form_url: "https://docs.google.com/forms/d/e/1FAIpQLSdCOuPg-FYezeIgNeGk2y5PTDCCXnasWxIWrkpIwszl7KrrPw/viewform?usp=sf_link"
cover_image: /assets/images/main/mix/pattern.jpg

permalink: "/:title"


# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

feed:
  collections:
    posts:
      path: "/index.xml"
