url: https://pnvang.github.io
baseurl: /

# Site settings
title: MN Booth
logo: mnbooth_120.png
email: info@mnbooth.com
description: "An affordable event photo booth provider serving Minneapolis and surrounding cities."


# Team names, titles and social links
people:
- name: Meng Vang
  pic: meng
  position: Co-Founder/CEO
  social:
    - title: facebook
      url: https://www.facebook.com/meng.vang.1238
    - title: instagram
      url: https://www.instagram.com/meng_hiluss_vang

- name: Phia Vang
  pic: phia
  position: Co-Founder
  social:
    - title: facebook
      url: https://www.facebook.com/phianvang
    - title: linkedin
      url: https://www.linkedin.com/in/phiavang

- name: Nou Vang
  pic: nou
  position: Co-Founder
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: http://twitter.com/jekyllrb
  - title: facebook
    url:
  - title: stack-overflow
    url: http://stackoverflow.com/questions/tagged/jekyll
  - title: bitbucket
    url: http://bitbucket.org/jekyll
  - title: github
    url: http://github.com/jekyll

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
