url: https://pnvang.github.io
baseurl:

# Site settings
title: MN Booth
title_first: MN
title_second: Booth
logo: mnbooth_120.png
email: info@mnbooth.com
description: "An affordable event photo booth provider serving Minneapolis and surrounding cities."


# Team names, titles and social links
people:
- name: Meng Vang
  pic: meng
  position: Co-Founder/CEO
  about: Meng is a long-distance runner with a personal best full marathon time of 4 hours and 34 minutes. Meng is also Founder and CEO of Mengv Photography.
  social:
    - title: facebook
      url: https://www.facebook.com/meng.vang.1238
    - title: instagram
      url: https://www.instagram.com/meng_hiluss_vang

- name: Phia Vang
  pic: phia
  position: Co-Founder
  about: Phia is a Software Engineer at one of the best company in Minnesota. Phia enjoys daydreaming about what he'll do if he won the Powerball.
  social:
    - title: facebook
      url: https://www.facebook.com/phianvang
    - title: linkedin
      url: https://www.linkedin.com/in/phiavang

- name: Nou Vang
  pic: nou
  position: Co-Founder
  about: Nou enjoys traveling and all things romantic. If Nou ever finds a Genie and had three wishes, it'd be to meet BTS, cure cancer, and free the Genie.
  # social:
  #   - title: twitter
  #     url: #
  #   - title: facebook
  #     url: #
  #   - title: google-plus
  #     url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://facebook.com/mnbooth
  - title: instagram
    url: http://instagram.com/mnbooth

# Postal address (add as many lines as necessary)
address:
  - line: 3481 Melrose Place
  - line: Beverly Hills, CA 90210

# Build settings
markdown: kramdown
permalink: pretty
